version: "3.6"
services:
  nginx_next:
    image: "nginx:latest"
    container_name: "nginx_ykweb"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/cert:/etc/nginx/cert
      - /root/conf.d:/etc/nginx/conf.d
    depends_on:
      - ykweb

  ykweb:
    build: .
    container_name: ykService
    volumes:
      - /root/cert:/yk-web/cert
      - /root/yk-web/server.js:/yk-web/src/server.js
    restart: always
